general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf NNUnet Kidney segmentation (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- NNUnetRunner
- BamfProcessorRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunner:
    in_data: nifti:mod=ct
    nnunet_task: Task779_Kidneys_KIRC
    nnunet_model: 3d_fullres
    roi: KIDNEY,NEOPLASM_MALIGNANT_PRIMARY,CYST

  BamfProcessorRunner:

  DsegConverter:
    source_segs: nifti:mod=seg
    model_name: Bamf NNUnet CT Kidney
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/bamf_nnunet_ct_kidney.seg.dcm