general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for MONAI Prostate158 MR Prostate zonal regions segmentation (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- Prostate158Runner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: 'mr'

  NiftiConverter:
    in_datas: dicom:mod=mr
    engine: dcm2niix

  Prostate158Runner:
    in_data: nifti:mod=mr
    apply_center_crop: True

  DsegConverter:
    source_segs: nifti:mod=seg:roi=PROSTATE_TRANSITION_ZONE,PROSTATE_PERIPHERAL_ZONE
    target_dicom: dicom:mod=mr
    model_name: 'Segmentation of prostate regions, Prostate158'
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/prostate158.seg.dcm