general:
  data_base_dir: /app/data
modules:
  NrrdImporter:
    input_dir: 'input_data'
    input_file_name: 'image.nrrd'
  TotalSegmentatorRunner:
    path_to_config_file: ""
    use_fast_mode: true
